### ISSUE TITLE
Foreign key violation after filter_by_sf()

### ISSUE THREAD

**Issue by langbein-daniel** [ipeaGIT/gtfstools#71] opened 2023-06-20 09:01 UTC
Thanks for providing this library with useful tools for GTFS feeds!

---

I have created an R script to extract a rectangular region of a GTFS feed using the `read_gtfs`, `filber_by_sf` and `write_gtfs` functions.

When validating the resulting GTFS feed, there is, however, a foreign key violation.

---

Here is the script used:

```R
#
# Parameters
#

MIN_LON <- 11
MAX_LON <- 11.5
MIN_LAT <- 49
MAX_LAT <- 49.5

IN <- "input.zip"
OUT <- "gtfs.zip"

library(sf)
library(gtfstools)

#
# Create bounding box
#

# Create a closed polygon. The first and last points are identical.
points <- rbind(c(MIN_LON, MIN_LAT), c(MAX_LON, MIN_LAT), c(MAX_LON, MAX_LAT), c(MIN_LON, MAX_LAT), c(MIN_LON, MIN_LAT))
polygon <-st_polygon(list(points))
print(polygon)

# Create a spatial object from the polygon
polygon_sfc <- st_sfc(polygon, crs = 4326)
print(polygon_sfc)

#
# Read, filter and save GTFS
#

gtfs_data <- read_gtfs(IN)
filtered_data <- filter_by_sf(gtfs_data, polygon_sfc)
write_gtfs(filtered_data, OUT)

print("Finished filtering GTFS data set.", quote=FALSE)
```

The resulting 5 MB GTFS file can be downloaded here: https://cloud.privacy1st.de/s/LtMqRgMp97eZxFq

The validation report of the original and the filtered GTFS feed can be downloaded here: https://cloud.privacy1st.de/s/AZYTFStwyMRBqPx

The GTFS data comes from https://www.delfi.de/ and has a CC-BY license. I'm happy to also provide the original 300 MB GTFS file, if it is required.

### Report of original GTFS feed

![image](https://github.com/ipeaGIT/gtfstools/assets/73987547/738464fb-8e9a-4887-b787-f08782e4aeac)

### Report of filtered GTFS feed

![image](https://github.com/ipeaGIT/gtfstools/assets/73987547/bb848084-ac14-4721-969c-e35d68670efc)

And with details unfolded:

![image](https://github.com/ipeaGIT/gtfstools/assets/73987547/4b8ed751-fb1c-4a2f-bf16-686e67b4c6bc)

**Comment by langbein-daniel** [comment] 2023-06-20 09:05
I have opened `transfers.txt` with LibreOffice Calc. When filtering all rows with empty `from_route_id`, we see that row 7171 is the first one which has a value:

![image](https://github.com/ipeaGIT/gtfstools/assets/73987547/809b8b26-da3f-4f4c-8b8d-23debf849f3f)

**Comment by dhersz** [comment] 2023-08-10 20:38
Hi @langbein-daniel, sorry for the long delay answering this issue. The problem is that any filtering function currently only looks at `from_stop_id` and `to_stop_id` when filtering the `transfers` table. That's definitely an issue with the implementation, as you can see, because transfers that refer to `route_id`s or `trip_id`s that have been filtered out from feed should probably be filtered out as well.

I'll try to fix this in the following days and will report back to this issue.

**Comment by dhersz** [comment] 2023-08-10 20:47
If you're still willing to share the original 300 MB feed, I'd like to download it and investigate this issue further. I'm curious to know why the referred route_id (`161965_3`) has been filtered out from the feed if apparently a stop that it should be able to use is still there.

If a stop_id has been kept in the feed (as in the case in `from_stop_id` and `to_stop_id`) it should probably mean that any trips that pass by this stop should be kept as well (`filter_by_sf()` currently uses `filter_by_trip_id()` behind the scenes), and, consequently, any routes linked to this trip. It seems a bit weird that a `from_route_id` is referring to a route_id that has been filtered out, but perhaps I have the wrong mental model in my mind.

**Comment by langbein-daniel** [comment] 2023-08-12 10:09
> If you're still willing to share the original 300 MB feed, I'd like to download it and investigate this issue further.

Here you are, thanks for having a look! https://cloud.privacy1st.de/s/X4jjNWS5jzojTQM

**Comment by langbein-daniel** [comment] 2023-08-12 10:19
> It seems a bit weird that a `from_route_id` is referring to a route_id that has been filtered out, but perhaps I have the wrong mental model in my mind.

It could also be due to bad quality of the GTFS feed itself. There are currently 40 issues regarding the DELFI GTFS feed over here https://github.com/mfdz/GTFS-Issues/labels/DELFI (partially in German).

One issue is about stops where passengers board/disembark vehicles having location_type exit/entrance. Maybe this could be related? https://github.com/mfdz/GTFS-Issues/issues/72

However, I hope that the error is not just from the dataset I am using and that I am now causing you hassle as a result. Good luck investigating the problem!

**Comment by dhersz** [comment] 2023-11-03 19:14
I'm finally working on this issue. 

> If you're still willing to share the original 300 MB feed, I'd like to download it and investigate this issue further. I'm curious to know why the referred route_id (`161965_3`) has been filtered out from the feed if apparently a stop that it should be able to use is still there.
> 
> If a stop_id has been kept in the feed (as in the case in `from_stop_id` and `to_stop_id`) it should probably mean that any trips that pass by this stop should be kept as well (`filter_by_sf()` currently uses `filter_by_trip_id()` behind the scenes), and, consequently, any routes linked to this trip. It seems a bit weird that a `from_route_id` is referring to a route_id that has been filtered out, but perhaps I have the wrong mental model in my mind.

I did in fact have the wrong mental model here. It's not that any trips that pass by the stops shown that should be kept in the table, but stops that compose the trips that remain after the filter that should be kept. I.e. the stops we're seeing in the table do appear in the stop_times table after the filter, but the mentioned route_id does not, because none of the trips that runs with this route are kept in the filtered feed.

Hard to explain in words, but well, fixing the issue (i.e. considering from/to_route_id and from/to_trip_id in the filter) will fix this behavior.

**Comment by dhersz** [comment] 2023-11-03 21:21
Hi @langbein-daniel. I believe the current dev version of the package should have this issue fixed. Do you mind trying it later? I tested on the dataset you made available earlier and it seems to be working. I'm sorry for taking so long to fix it.

As a follow-up to this issue, I'll add transfers filtering from route/trip_id to the other available functions and probably add another sample feed to the package to use in tests, as the current available samples do not include transfers tables with from/to_route/trip_id.

**Comment by dhersz** [comment] 2023-11-28 13:15
Closing the issue for now. Feel free to open if you find that the changes do not fix the problem.

**Closed by dhersz** 2023-11-28 13:15 UTC
